test.profile=PRD_PROFILE_DESKTOP
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:/keys/subrestapi-ssl.p12
server.ssl.key-store-password=${JWT_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=subrestapi

# OracleDB connection settings
spring.datasource.url=jdbc:oracle:thin:@192.168.1.153:1521/APEXPRD
spring.datasource.username=DEV_JSB_APP_USER
spring.datasource.password=${AUTHJSB_DB_PASSWORD}

# UCP settings
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.initial-pool-size=5
spring.datasource.oracleucp.min-pool-size=5
spring.datasource.oracleucp.max-pool-size=10

#
jwt.keystore.location=/keys/authserver-keystore.p12
jwt.key.alias=authserver
jwt.keystore.password=${JWT_KEYSTORE_PASSWORD}
jwt.key.password=${JWT_KEY_PASSWORD}


