management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=ALWAYS
management.info.env.enabled=true
info.application.name=PersJSB
info.application.description=A demo application to showcase Springboot and Oracle DB integration using Oracle UCP as Connection Pool.  
info.application.author=Naveen Paulraj
info.application.version='@project.version@'
info.app.name=PersJSB
info.app.description=Person CRUD API
info.app.version=2.0
info.company.name=N4SoftSol
info.company.environment=Production
#
management.endpoints.web.cors.allowed-origin-patterns=https://*.n4softsol.com,http://localhost:4200
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
management.endpoints.web.cors.allowed-headers=*
management.endpoints.web.cors.allow-credentials=true
#
spring.profiles.active=dev